### ISSUE TITLE
Need a way to identify mobile/web/desktop

### ISSUE THREAD

**Issue by neymarsabin** [neymarsabin/nepali-apps#2]
We might need to add tags to each URLs to identify them as either mobile/desktop/web apps or combination of them.
something like this:-
```
[FonePay](https://fonepay.com.np)    #web #desktop #mobile
```

**Comment by skyGtm** [comment]
as the list increases we might find apps which is available in website, desktop software, android and iOS apps, so i think it would be better to list it in tabular form
'**N/A**' to indicate the program is unavailable in given platform.


## Money

| Software Name       | Description                                    | Website                      | Desktop Software | Android App | iOS App |
|---------------------|------------------------------------------------|------------------------------|------------------|-------------|---------|
| Example Money App   | A finance management app for personal budgets  | [Link](http://example.com)  | [Link](http://example.com/desktop) | [Link](http://example.com/android) | N/A |

## Accounting

| Software Name          | Description                                    | Website                         | Desktop Software | Android App | iOS App |
|------------------------|------------------------------------------------|---------------------------------|------------------|-------------|---------|
| Example Accounting    | Accounting software for small businesses       | [Link](http://example.com)     | N/A | [Link](http://example.com/android) | [Link](http://example.com/ios) |

## Audiobooks

| Software Name      | Description                                    | Website                          | Desktop Software | Android App | iOS App |
|--------------------|------------------------------------------------|----------------------------------|------------------|-------------|---------|
| Example Audiobook  | Audiobook player with various features        | N/A | [Link](http://example.com/desktop) | [Link](http://example.com/android) | N/A |

## News

| Software Name    | Description                                    | Website                        | Desktop Software | Android App | iOS App |
|------------------|------------------------------------------------|--------------------------------|------------------|-------------|---------|
| Example News App | App for reading latest news articles           | N/A | N/A | [Link](http://example.com/android) | [Link](http://example.com/ios) |

## Ecommerce

| Software Name        | Description                                    | Website                         | Desktop Software | Android App | iOS App |
|----------------------|------------------------------------------------|---------------------------------|------------------|-------------|---------|
| Example Ecommerce   | Ecommerce platform for small businesses       | [Link](http://example.com)     | [Link](http://example.com/desktop) | N/A | N/A |

**Comment by neymarsabin** [comment]
Thanks @skyGtm, this is a good idea. Also, keep in mind that we will be building a JSON server based on the list here. Anything that favors both will work for me.

**Comment by skyGtm** [comment]
instead of editing markdown file, i think it would be better we start listing apps in YAML file(instead of .md file because new contributers who have no knowledge of .md file can easily read YAML and populate respective fields), then we can write python script to parse YAML and generate JSON file and markdown file for easy viewing. This python script can be set to run after merging pull request, via Github CI

**Comment by neymarsabin** [comment]
YAML is not a good choice here. I don't think people who know YAML wouldn't know JSON. Let's not worry about people not knowing JSON and I believe this is not a problem. Let tell you what I am thinking:

Build a JSON array to build the list. We will have a process that can read JSON pipe the output to markdown as well as serve the JSON array. The benefit of doing this is we can build a monorepo to serve the client too.

**Comment by jguzej** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
vicioux, @yds05238, @baronPortalverse, @rsydn9, @chase-lee, @Harrolee, @herbqiao, @gmkhanrabbani, @1Bittium, @Regloom, @nexeck, @viviyorg, @0x-ultra, @puffdood, @pikonha, @garthmortensen, @yxiZo, @nulldataset, @anhskohbo, @liubaojunsh, @duyuefeng0708, @Sunil4510, @angristan, @zdrift3r, @magnetism2000, @XiFYuW, @ercu, @androiddk1, @MissLov3ly, @Semsert16, @naoki914, @chubetho, @tgmarinho, @laurentnguyen, @tolgayayci, @Evanlai8, @chronick, @milescristi, @ColorCamo, @samirdjelal, @rpopplewell, @lazy1523, @Sigmus, @YamineRL, @bininvest, @Kuba260484, @ultra-supara, @echo672, @Rylai-Zihang, @Lina-Jin

**Comment by batu07040** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
0xtangping, @ronnath, @dongchuant, @boombb12138, @munj1, @clark-cui, @vloddos, @cvs0, @gidonkatten, @MoodyReaper, @Alex31122, @dolylupec, @0xRichardH, @mrthedude, @Ajand, @milaabl, @baoanh1310, @lostguo, @sondcdev, @Thejineaswar, @ClaviXeno, @Pent, @huxin1997, @avrillucy, @JanetMo, @cvvbbo, @r3dtap3, @LeonLespri, @shubhampatel27, @yisonr, @kekonen, @pandaplusplus, @anylots, @kopasxa, @, @jsyanyang, @YellowRedTrader, @grkhr, @Missingol-Promnica, @faubricioforester, @Pratyum, @Crypgalpal, @r00-tz, @Fuuurma, @Frago9876543210, @kmlcnclk, @devolaw, @deepakkashyap3013, @akikoeth, @zheng100
